# Generated by Django 4.2 on 2023-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='typePersonnage',
            field=models.CharField(choices=[('Archer', 'Archer'), ('Magician', 'Magician'), ('Barbarian', 'Barbarian'), ('Paladin', 'Paladin'), ('Monster', 'Monster')], default='Archer', max_length=25),
        ),
    ]
