# Generated by Django 4.2 on 2023-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_typepersonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='enemyDamage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='enemyHp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='enemyMaxHp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='idEnemy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
