# Generated by Django 4.2 on 2023-04-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_enemydamage_game_enemyhp_game_enemymaxhp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
