# Generated by Django 4.2 on 2023-04-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('rage', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('crit_rate', models.IntegerField()),
                ('crit_dmg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('armor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='armor.armor')),
                ('type', models.CharField(choices=[('Helmet', 'Helmet'), ('Chestplate', 'Chestplate'), ('Leggings', 'Leggings'), ('Boots', 'Boots')], default='Boots', max_length=25)),
            ],
            bases=('armor.armor',),
        ),
        migrations.CreateModel(
            name='Chestplate',
            fields=[
                ('armor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='armor.armor')),
                ('type', models.CharField(choices=[('Helmet', 'Helmet'), ('Chestplate', 'Chestplate'), ('Leggings', 'Leggings'), ('Boots', 'Boots')], default='Chestplate', max_length=25)),
            ],
            bases=('armor.armor',),
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('armor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='armor.armor')),
                ('type', models.CharField(choices=[('Helmet', 'Helmet'), ('Chestplate', 'Chestplate'), ('Leggings', 'Leggings'), ('Boots', 'Boots')], default='Helmet', max_length=25)),
            ],
            bases=('armor.armor',),
        ),
        migrations.CreateModel(
            name='Leggings',
            fields=[
                ('armor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='armor.armor')),
                ('type', models.CharField(choices=[('Helmet', 'Helmet'), ('Chestplate', 'Chestplate'), ('Leggings', 'Leggings'), ('Boots', 'Boots')], default='Leggings', max_length=25)),
            ],
            bases=('armor.armor',),
        ),
    ]
