# Generated by Django 4.2 on 2023-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0002_armor_starter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='starter',
            field=models.IntegerField(choices=[(1, 'Vrai'), (0, 'Faux')], default=0),
        ),
    ]
