# Generated by Django 4.2 on 2023-04-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0003_alter_armor_starter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'managed': False},
        ),
    ]
