# Generated by Django 4.2 on 2023-04-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Bow', 'Bow'), ('Staff', 'Staff'), ('Mass', 'Mass'), ('Shield', 'Shield'), ('Hatchet', 'Hatchet')], max_length=25)),
                ('damage', models.IntegerField()),
                ('defense', models.IntegerField()),
            ],
        ),
    ]
