# Generated by Django 4.2 on 2023-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='starter',
            field=models.IntegerField(choices=[(1, 'Vrai'), (0, 'Faux')], default=0),
        ),
    ]
