# Generated by Django 4.2 on 2023-04-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('armor', '0001_initial'),
        ('weapon', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('tokens', models.JSONField()),
                ('state', models.IntegerField()),
                ('type', models.CharField(choices=[('Archer', 'Archer'), ('Magician', 'Magician'), ('Barbarian', 'Barbarian'), ('Paladin', 'Paladin')], default='Archer', max_length=25)),
                ('boots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armor.boots')),
                ('chestplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armor.chestplate')),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armor.helmet')),
                ('leggings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armor.leggings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapon.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.character')),
            ],
            bases=('characters.character',),
        ),
        migrations.CreateModel(
            name='Barbarian',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.character')),
            ],
            bases=('characters.character',),
        ),
        migrations.CreateModel(
            name='Magician',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.character')),
            ],
            bases=('characters.character',),
        ),
        migrations.CreateModel(
            name='Paladin',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.character')),
                ('shield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapon.weapon')),
            ],
            bases=('characters.character',),
        ),
        migrations.DeleteModel(
            name='Characters',
        ),
    ]
