# Generated by Django 4.2 on 2023-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_archer_barbarian_magician_paladin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archer',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='barbarian',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='magician',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paladin',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
