# Generated by Django 4.2 on 2023-04-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_archer_name_barbarian_name_magician_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='barbarian',
            name='name',
        ),
        migrations.RemoveField(
            model_name='magician',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paladin',
            name='name',
        ),
        migrations.AddField(
            model_name='archer',
            name='basic_hp',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='archer',
            name='mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='barbarian',
            name='basic_hp',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='barbarian',
            name='rage',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='magician',
            name='basic_hp',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='magician',
            name='mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='paladin',
            name='basic_hp',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='paladin',
            name='rage',
            field=models.IntegerField(default=50),
        ),
    ]
