# Generated by Django 4.2 on 2023-04-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_archer_name_remove_barbarian_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'managed': False},
        ),
    ]
