# Generated by Django 4.2 on 2023-04-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_character_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={},
        ),
    ]
