# Generated by Django 4.2 on 2023-04-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_character_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
    ]
