# Generated by Django 4.2 on 2023-04-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_character_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'managed': False},
        ),
    ]
