# Generated by Django 4.2 on 2023-04-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_character_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='archer',
            name='basic_mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='barbarian',
            name='basic_rage',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='magician',
            name='basic_mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='paladin',
            name='basic_rage',
            field=models.IntegerField(default=50),
        ),
    ]
