# Generated by Django 4.2 on 2023-04-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_archer_basic_mana_barbarian_basic_rage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.character')),
            ],
            bases=('characters.character',),
        ),
    ]
