# Generated by Django 4.2 on 2023-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_alter_character_boots_alter_character_chestplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
        migrations.AddField(
            model_name='character',
            name='typeCharacter',
            field=models.CharField(choices=[('Archer', 'Archer'), ('Magician', 'Magician'), ('Barbarian', 'Barbarian'), ('Paladin', 'Paladin'), ('Monster', 'Monster')], default='Archer', max_length=25),
        ),
    ]
