# Generated by Django 4.2 on 2023-04-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0004_alter_armor_options'),
        ('weapon', '0002_weapon_starter'),
        ('characters', '0013_remove_character_type_character_typecharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armor.boots'),
        ),
        migrations.AlterField(
            model_name='character',
            name='chestplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armor.chestplate'),
        ),
        migrations.AlterField(
            model_name='character',
            name='helmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armor.helmet'),
        ),
        migrations.AlterField(
            model_name='character',
            name='leggings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armor.leggings'),
        ),
        migrations.AlterField(
            model_name='character',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='tokens',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapon.weapon'),
        ),
    ]
