# Generated by Django 4.2 on 2023-04-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_alter_character_boots_alter_character_chestplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='tokensAvailable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
