# Generated by Django 4.2 on 2023-04-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
        ('characters', '0016_alter_character_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='tokens',
        ),
        migrations.AddField(
            model_name='character',
            name='tokens',
            field=models.ManyToManyField(to='tokens.tokens'),
        ),
    ]
